apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: random-bojack-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: www.bojack-app.vaibhavkumar.me
      http:
        paths:
          - backend:
              serviceName: random-bojack-app
              servicePort: 3000
            path: /
